### ISSUE TITLE
API error?

### ISSUE THREAD

**Issue by rogueyoshi** [lunar-phase/smashgg-results#2]
`PS C:\Users\sx-stream\Documents\GitHub\smashgg-results> node index.js battle-over-the-bridge-1
TypeError: Cannot read property 'externalUsername' of undefined
    at C:\Users\sx-stream\Documents\GitHub\smashgg-results\index.js:86:46
    at Array.map (<anonymous>)
    at placingString (C:\Users\sx-stream\Documents\GitHub\smashgg-results\index.js:86:6)
    at Array.map (<anonymous>)
    at main (C:\Users\sx-stream\Documents\GitHub\smashgg-results\index.js:67:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

Do I need to specify token access levels? Did `npm i` but not sure why it's not working. Token is plaintext in `SMASHGG_TOKEN` file.

**Comment by rogueyoshi** [comment]
PR with fix: https://github.com/lunar-phase/smashgg-results/pull/3

EDIT: Not sure what broke the parsing change originally, but my node version is v14.17.3. [Here's my package-lock for reference.](https://github.com/rogueyoshi/smashgg-results/blob/master/package-lock.json)
